DROP TABLE IF EXISTS Jugadores;
DROP TABLE IF EXISTS estadios;
DROP TABLE IF EXISTS clubes;
DROP TABLE IF EXISTS Usuarios;
DROP TABLE IF EXISTS Partidas;



CREATE TABLE Jugadores (
    id INT PRIMARY KEY,
    cantGoles INT,
    nombre VARCHAR(500),
    pais VARCHAR(500)
);

CREATE TABLE Usuarios (
    idUser INT PRIMARY KEY,
    username VARCHAR(50),
    email VARCHAR(50),
    contrasenia VARCHAR(50),
    record INT,
    esAdmin BOOL
    );

CREATE TABLE Partidas (
    idJuego INT PRIMARY KEY,
    idUser INT,
    fecha DATE,
    puntuacion INT,
    FOREIGN KEY (idUser) REFERENCES Usuarios(idUser)
);


INSERT INTO Jugadores (id, cantGoles, nombre, pais) VALUES
(1, 16, 'Miroslav Klose', 'Alemania'),
(2, 15, 'Ronaldo Nazário', 'Brasil'),
(3, 14, 'Gerd Müller', 'Alemania'),
(4, 13, 'Just Fontaine', 'Francia'),
(5, 13, 'Lionel Messi', 'Argentina'),
(6, 12, 'Kylian Mbappé', 'Francia'),
(7, 12, 'Pelé', 'Brasil'),
(8, 11, 'Jürgen Klinsmann', 'Alemania'),
(9, 11, 'Sándor Kocsis', 'Hungría'),
(10, 10, 'Gabriel Batistuta', 'Argentina'),
(11, 10, 'Gary Lineker', 'Inglaterra'),
(12, 10, 'Grzegorz Lato', 'Polonia'),
(13, 10, 'Teófilo Cubillas', 'Perú'),
(14, 10, 'Thomas Müller', 'Alemania'),
(15, 9, 'Ademir', 'Brasil'),
(16, 9, 'Christian Vieri', 'Italia'),
(17, 9, 'David Villa', 'España'),
(18, 9, 'Eusébio', 'Portugal'),
(19, 9, 'Jairzinho', 'Brasil'),
(20, 9, 'Karl-Heinz Rummenigge', 'Alemania'),
(21, 9, 'Paolo Rossi', 'Italia'),
(22, 9, 'Roberto Baggio', 'Italia'),
(23, 9, 'Vavá', 'Brasil'),
(24, 8, 'Cristiano Ronaldo', 'Portugal'),
(25, 8, 'Diego Maradona', 'Argentina'),
(26, 8, 'Guillermo Stábile', 'Argentina'),
(27, 8, 'Harry Kane', 'Inglaterra'),
(28, 8, 'Leônidas', 'Brasil'),
(29, 8, 'Neymar Jr.', 'Brasil'),
(30, 8, 'Oscar Míguez', 'Uruguay'),
(31, 8, 'Rivaldo', 'Brasil'),
(32, 8, 'Rudi Völler', 'Alemania'),
(33, 7, 'Andrzej Szarmach', 'Polonia'),
(34, 7, 'Careca', 'Brasil'),
(35, 7, 'Hans Schäfer', 'Alemania'),
(36, 7, 'Johnny Rep', 'Países Bajos'),
(37, 7, 'Lajos Tichy', 'Hungría'),
(38, 7, 'Luis Suárez', 'Uruguay'),
(39, 6, 'Arjen Robben', 'Países Bajos'),
(40, 6, 'Asamoah Gyan', 'Ghana'),
(41, 6, 'Davor Šuker', 'Croacia'),
(42, 6, 'Dennis Bergkamp', 'Países Bajos'),
(43, 6, 'Diego Forlán', 'Uruguay'),
(44, 6, 'Enner Valencia', 'Ecuador'),
(45, 6, 'György Sárosi', 'Hungría'),
(46, 10, 'Helmut Rahn', 'Alemania'),
(47, 6, 'Hristo Stoichkov', 'Bulgaria'),
(48, 6, 'Ivan Perišić', 'Croacia'),
(49, 6, 'James Rodríguez', 'Colombia'),
(50, 6, 'Josef Hügi', 'Suiza'),
(51, 6, 'Lothar Matthäus', 'Alemania'),
(52, 6, 'Mario Kempes', 'Argentina'),
(53, 6, 'Max Morlock', 'Alemania'),
(54, 6, 'Robin van Persie', 'Países Bajos'),
(55, 6, 'Salvatore Schillaci', 'Italia'),
(56, 6, 'Thierry Henry', 'Francia'),
(57, 6, 'Wesley Sneijder', 'Países Bajos'),
(58, 6, 'Zbigniew Boniek', 'Polonia'),
(59, 5, 'Alessandro Altobelli', 'Italia'),
(60, 5, 'Erich Probst', 'Austria'),
(61, 5, 'Edinson Cavani', 'Uruguay'),
(62, 5, 'Emilio Butragueño', 'España'),
(63, 5, 'Fernando Hierro', 'España'),
(64, 5, 'Fernando Morientes', 'España'),
(65, 5, 'Franz Beckenbauer', 'Alemania'),
(66, 5, 'Garrincha', 'Brasil'),
(67, 5, 'Geoff Hurst', 'Inglaterra'),
(68, 5, 'Gonzalo Higuaín', 'Argentina'),
(69, 5, 'Henrik Larsson', 'Suecia'),
(70, 5, 'Jon Dahl Tomasson', 'Dinamarca'),
(71, 5, 'Landon Donovan', 'Estados Unidos'),
(72, 5, 'Lukas Podolski', 'Alemania'),
(73, 5, 'Marc Wilmots', 'Bélgica'),
(74, 5, 'Mario Mandžukić', 'Croacia'),
(75, 5, 'Michel Platini', 'Francia'),
(76, 5, 'Olivier Giroud', 'Francia'),
(78, 5, 'Peter Beardsley', 'Inglaterra'),
(79, 5, 'Raúl González', 'España'),
(80, 5, 'Roger Milla', 'Camerún'),
(81, 5, 'Romário', 'Brasil'),
(82, 5, 'Romelu Lukaku', 'Bélgica'),
(83, 5, 'Silvio Piola', 'Italia'),
(84, 5, 'Thomas Skuhravý', 'República Checa'),
(85, 5, 'Tim Cahill', 'Australia'),
(86, 5, 'Xherdan Shaqiri', 'Suiza'),
(87, 5, 'Zico', 'Brasil'),
(88, 5, 'Zinedine Zidane', 'Francia'),
(89, 4, 'Andreas Brehme', 'Alemania'),
(90, 4, 'Antoine Griezmann', 'Francia'),
(91, 4, 'Bebeto', 'Brasil'),
(92, 4, 'Bobby Charlton', 'Inglaterra'),
(93, 4, 'Claudio Caniggia', 'Argentina'),
(94, 4, 'Clint Dempsey', 'Estados Unidos'),
(95, 4, 'Daniel Bertoni', 'Argentina'),
(96, 4, 'Ferenc Puskás', 'Hungría'),
(97, 4, 'Fernando Torres', 'España'),
(98, 4, 'Hernán Crespo', 'Argentina'),
(99, 4, 'Igor Belanov', 'Ucrania'),
(101, 4, 'Javier Hernández', 'México'),
(102, 4, 'Jorge Valdano', 'Argentina'),
(103, 4, 'Julián Álvarez', 'Argentina'),
(104, 4, 'Kennet Andersson', 'Suecia'),
(105, 4, 'Leopoldo Luque', 'Argentina'),
(106, 4, 'Martin Dahlin', 'Suecia'),
(107, 4, 'Michael Owen', 'Inglaterra'),
(108, 4, 'Paul Breitner', 'Alemania'),
(109, 4, 'Preben Elkjær', 'Dinamarca'),
(110, 4, 'René Houseman', 'Argentina'),
(111, 2, 'Ronaldinho', 'Brasil'),
(112, 4, 'Sócrates', 'Brasil'),
(113, 3, 'Yerry Mina', 'Colombia'),
(114, 4, 'Gino Colaussi', 'Italia'),
(115, 3, 'Alessandro Del Piero', 'Italia'),
(116, 3, 'Álvaro Morata', 'España'),
(117, 3, 'Cody Gakpo', 'Países Bajos'),
(118, 3, 'Daniel Passarella', 'Argentina'),
(119, 3, 'David Beckham', 'Inglaterra'),
(120, 1, 'David Trezeguet', 'Francia'),
(121, 3, 'Eden Hazard', 'Bélgica'),
(122, 3, 'Enzo Scifo', 'Bélgica'),
(123, 3, 'Filippo Inzaghi', 'Italia'),
(125, 3, 'Gheorghe Hagi', 'Rumania'),
(126, 3, 'Gianni Rivera', 'Italia'),
(127, 3, 'Gonçalo Ramos', 'Portugal'),
(128, 3, 'Johan Cruyff', 'Países Bajos'),
(129, 3, 'Jorge Burruchaga', 'Argentina'),
(130, 3, 'Karim Benzema', 'Francia'),
(131, 3, 'Marcus Rashford', 'Inglaterra'),
(132, 3, 'Maxi Rodríguez', 'Argentina'),
(133, 3, 'Memphis Depay', 'Países Bajos'),
(134, 3, 'Michael Ballack', 'Alemania'),
(135, 3, 'Michael Laudrup', 'Dinamarca'),
(136, 3, 'Patrick Kluivert', 'Países Bajos'),
(137, 3, 'Richarlison', 'Brasil'),
(138, 3, 'Samuel Eto''o', 'Camerún'),
(139, 3, 'Son Heung-min', 'Corea del Sur'),
(140, 3, 'Steven Gerrard', 'Inglaterra'),
(141, 3, 'Toni Kroos', 'Alemania'),
(142, 1, 'Xabi Alonso', 'España'),
(143, 3, 'Ángel Di María', 'Argentina'),
(144, 3, 'Carlos Tévez', 'Argentina'),
(145, 3, 'Bukayo Saka', 'Inglaterra'),
(146, 3, 'Paul Pogba', 'Francia'),
(148, 1, 'Marc Overmars', 'Países Bajos'),
(149, 3, 'Rafael Márquez', 'México'),
(150, 2, 'Alan Shearer', 'Inglaterra'),
(151, 2, 'Alexis Sánchez', 'Chile'),
(152, 2, 'Andrés Iniesta', 'España'),
(153, 2, 'Ariel Ortega', 'Argentina'),
(154, 2, 'Bastian Schweinsteiger', 'Alemania'),
(156, 2, 'Daniele De Rossi', 'Italia'),
(157, 2, 'Didier Drogba', 'Costa de Marfil'),
(158, 2, 'Emmanuel Petit', 'Francia'),
(159, 2, 'Francesco Totti', 'Italia'),
(160, 2, 'Juan Fernando Quintero', 'Colombia'),
(161, 2, 'Kaká', 'Brasil'),
(162, 2, 'Kevin De Bruyne', 'Bélgica'),
(163, 2, 'Luka Modrić', 'Croacia'),
(164, 2, 'Mesut Özil', 'Alemania'),
(165, 2, 'Mohamed Salah', 'Egipto'),
(166, 2, 'Robert Lewandowski', 'Polonia'),
(167, 2, 'Aleksandar Mitrović', 'Serbia'),
(168, 2, 'Alphonso Davies', 'Canadá'),
(169, 2, 'Andrej Kramarić', 'Croacia'),
(170, 2, 'Boulaye Dia', 'Senegal'),
(171, 2, 'Breel Embolo', 'Suiza'),
(172, 2, 'Bruno Fernandes', 'Portugal'),
(173, 2, 'Casemiro', 'Brasil'),
(174, 2, 'Cho Gue-sung', 'Corea del Sur'),
(175, 2, 'Christian Eriksen', 'Dinamarca'),
(176, 2, 'Deco', 'Portugal'),
(177, 2, 'Gareth Bale', 'Gales'),
(178, 2, 'Giorgian de Arrascaeta', 'Uruguay'),
(179, 2, 'Hakim Ziyech', 'Marruecos'),
(180, 2, 'Jude Bellingham', 'Inglaterra'),
(181, 2, 'Kai Havertz', 'Alemania'),
(183, 2, 'Marko Livaja', 'Croacia'),
(184, 2, 'Mohammed Kudus', 'Ghana'),
(185, 2, 'Niclas Füllkrug', 'Alemania'),
(187, 2, 'Rafael Leão', 'Portugal'),
(188, 2, 'Ritsu Doan', 'Japón'),
(189, 2, 'Rui Costa', 'Portugal'),
(190, 2, 'Salem Al-Dawsari', 'Arabia Saudita'),
(191, 2, 'Sergio Agüero', 'Argentina'),
(192, 2, 'Thiago Silva', 'Brasil'),
(193, 2, 'Vincent Aboubakar', 'Camerún'),
(194, 2, 'Vinícius Júnior', 'Brasil'),
(195, 2, 'Youssef En-Nesyri', 'Marruecos'),
(196, 2, 'İlkay Gündoğan', 'Alemania'),
(197, 2, 'Jared Borgetti', 'México'),
(198, 2, 'Luis Hernández', 'México'),
(199, 2, 'Hidetoshi Nakata', 'Japón'),
(201, 2, 'Robbie Keane', 'Irlanda'),
(202, 2, 'Keisuke Honda', 'Japón'),
(203, 2, 'Henri Camara', 'Senegal'),
(204, 2, 'Tim Borowski', 'Alemania'),
(205, 2, 'Phillip Cocu', 'Países Bajos'),
(206, 2, 'Ronald de Boer', 'Países Bajos'),
(207, 1, 'Claudio López', 'Argentina'),
(208, 2, 'Cuauhtémoc Blanco', 'México'),
(209, 2, 'Brian McBride', 'Estados Unidos'),
(210, 2, 'Mile Jedinak', 'Australia'),
(211, 2, 'Ahmed Musa', 'Nigeria'),
(212, 2, 'Salomon Kalou', 'Costa de Marfil'),
(213, 2, 'Nelson Valdez', 'Paraguay'),
(214, 2, 'Milan Baroš', 'República Checa'),
(215, 2, 'Fred', 'Brasil'),
(216, 2, 'Hakan Şükür', 'Turquía'),
(217, 2, 'Ilhan Mansiz', 'Turquía'),
(218, 2, 'Ji-sung Park', 'Corea del Sur'),
(219, 2, 'Ahn Jung-hwan', 'Corea del Sur'),
(220, 2, 'Benni McCarthy', 'Sudáfrica'),
(221, 2, 'Granit Xhaka', 'Suiza'),
(222, 2, 'Andreas Granqvist', 'Suecia'),
(223, 2, 'John Stones', 'Inglaterra'),
(224, 2, 'Michy Batshuayi', 'Bélgica'),
(226, 2, 'Luís Fabiano', 'Brasil'),
(228, 2, 'Edmílson', 'Brasil'),
(229, 2, 'Wilfried Bony', 'Costa de Marfil'),
(230, 2, 'Gervinho', 'Costa de Marfil'),
(231, 2, 'Giovani dos Santos', 'México'),
(232, 2, 'Andrés Guardado', 'México'),
(233, 2, 'Oribe Peralta', 'México'),
(234, 2, 'Mathew Leckie', 'Australia'),
(235, 2, 'Shinji Kagawa', 'Japón'),
(236, 2, 'Takashi Inui', 'Japón'),
(238, 2, 'Yuri Djorkaeff', 'Francia'),
(239, 2, 'Luigi Riva', 'Italia'),
(240, 2, 'Adrian Mutu', 'Rumania'),
(241, 2, 'Eduardo da Silva', 'Croacia'),
(242, 1, 'Milan Rapaić', 'Croacia'),
(243, 2, 'Daniel Van Buyten', 'Bélgica'),
(244, 2, 'Wilfried Zaha', 'Costa de Marfil'),
(246, 2, 'Stephen Appiah', 'Ghana'),
(248, 2, 'Alexander Frei', 'Suiza'),
(250, 2, 'Hakan Yakın', 'Suiza'),
(251, 1, 'Adrien Rabiot', 'Francia'),
(252, 1, 'Alexis Mac Allister', 'Argentina'),
(253, 1, 'Andrea Pirlo', 'Italia'),
(254, 1, 'Aurélien Tchouaméni', 'Francia'),
(255, 1, 'Carles Puyol', 'España'),
(256, 1, 'Carlos Alberto', 'Brasil'),
(257, 1, 'Enzo Fernández', 'Argentina'),
(258, 1, 'Franck Ribéry', 'Francia'),
(259, 1, 'Javier Zanetti', 'Argentina'),
(260, 1, 'José Luis Brown', 'Argentina'),
(261, 1, 'Maicon', 'Brasil'),
(262, 1, 'Oscar Ruggeri', 'Argentina'),
(263, 1, 'Paul Scholes', 'Inglaterra'),
(264, 1, 'Philipp Lahm', 'Alemania'),
(265, 1, 'Yaya Touré', 'Costa de Marfil'),
(268, 1, 'Isco', 'España'),
(269, 1, 'Nani', 'Portugal'),
(270, 1, 'Ricardo Quaresma', 'Portugal'),
(271, 1, 'Raheem Sterling', 'Inglaterra'),
(272, 1, 'Jack Grealish', 'Inglaterra'),
(273, 1, 'Jordan Henderson', 'Inglaterra'),
(275, 1, 'Harry Maguire', 'Inglaterra'),
(276, 1, 'Jesse Lingard', 'Inglaterra'),
(277, 1, 'Dele Alli', 'Inglaterra'),
(278, 1, 'Kieran Trippier', 'Inglaterra'),
(279, 2, 'Mario Götze', 'Alemania'),
(280, 2, 'Mats Hummels', 'Alemania'),
(281, 2, 'Sami Khedira', 'Alemania'),
(283, 2, 'Marcos Rojo', 'Argentina'),
(284, 1, 'Gabriel Mercado', 'Argentina'),
(287, 1, 'Roberto Firmino', 'Brasil'),
(288, 1, 'Paulinho', 'Brasil'),
(290, 1, 'Lucas Paquetá', 'Brasil'),
(291, 1, 'Marco Asensio', 'España'),
(292, 1, 'Gavi', 'España'),
(293, 1, 'Dani Olmo', 'España'),
(295, 1, 'Raphaël Varane', 'Francia'),
(296, 1, 'Samuel Umtiti', 'Francia'),
(297, 1, 'Laurent Blanc', 'Francia');

